/*
  Block Character
  by J-Toastie
  via Poly Pizza (https://poly.pizza/m/ozSIyRIcIj)

  License: CC-BY (https://creativecommons.org/licenses/by/3.0/)
  Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useAnimations, useGLTF } from '@react-three/drei'
import { useGraph, type ObjectMap } from '@react-three/fiber'
import { useEffect, useMemo, useRef, useState, type JSX } from 'react'
import type {
  Bone,
  ColorRepresentation,
  Group,
  Material,
  MeshStandardMaterial,
  SkinnedMesh,
} from 'three'
import type { GLTF } from 'three-stdlib'
import { SkeletonUtils } from 'three/examples/jsm/Addons.js'

type GLTFResult = GLTF &
  ObjectMap & {
    nodes: {
      Player_1: SkinnedMesh
      Player_2: SkinnedMesh
      Root: Bone
    }
    materials: {
      body: MeshStandardMaterial
      eye_color: MeshStandardMaterial
    }
  }

type ActionName = 'Armature|Jump.001' | 'Armature|Walk'

export type BlockCharacterProps = JSX.IntrinsicElements['group'] & {
  color?: ColorRepresentation
  animate?: boolean
  action?: ActionName
}

export function BlockCharacter({
  color = 'white',
  animate,
  action = 'Armature|Walk',
  ...props
}: BlockCharacterProps) {
  const group = useRef<Group>(null)
  const { scene, materials, animations } = useGLTF('/models/block-character.glb') as GLTFResult
  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes } = useGraph(clone) as GLTFResult
  const { actions } = useAnimations(animations, group)

  const [bodyMaterial, setBodyMaterial] = useState<Material>()

  useEffect(() => {
    const bodyMaterial = materials.body.clone()
    bodyMaterial.color.set(color)
    setBodyMaterial(bodyMaterial)
  }, [materials, color])

  useEffect(() => {
    if (animate) actions[action]?.reset().fadeIn(0.5).play()
    else actions[action]?.fadeOut(0.5)
  }, [actions, action, animate])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Root_Scene">
        <group name="RootNode">
          <group name="Player" rotation={[-Math.PI / 2, 0, 0]} scale={55.481}>
            <skinnedMesh
              castShadow
              name="Player_1"
              geometry={nodes.Player_1.geometry}
              material={bodyMaterial}
              skeleton={nodes.Player_1.skeleton}
            />
            <skinnedMesh
              castShadow
              name="Player_2"
              geometry={nodes.Player_2.geometry}
              material={materials.eye_color}
              skeleton={nodes.Player_2.skeleton}
            />
          </group>
          <group name="Armature" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <primitive object={nodes.Root} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/block-character.glb')
